# Generated by Django 4.0.2 on 2022-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productlink',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='productphoto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='productprice',
            field=models.CharField(max_length=120),
        ),
    ]
