# Generated by Django 4.0.2 on 2022-02-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_productlink_alter_product_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productlink',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='productphoto',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
